clean:
	-del -f *.exe
	
all:  test 01_StreamInputOutput 02_GuessTheNumber 03_StringClass 04_VectorClass 05_Algorithms

test: test.cpp
	g++ -o test test.cpp
	
01_StreamInputOutput: 01_StreamInputOutput.cpp
	g++ -o 01_StreamInputOutput 01_StreamInputOutput.cpp

02_GuessTheNumber: 02_GuessTheNumber.cpp
	g++ -o 02_GuessTheNumber 02_GuessTheNumber.cpp
	
03_StringClass: 03_StringClass.cpp
	g++ -o 03_StringClass 03_StringClass.cpp

04_VectorClass: 04_VectorClass.cpp
	g++ -o 04_VectorClass 04_VectorClass.cpp

05_Algorithms: 05_Algorithms.cpp
	g++ -o 05_Algorithms 05_Algorithms.cpp	
