clean:
	-del -f *.exe
	
all:  test 01_Initialization 02_RoundoffError 03_StringInitialization 04_Const

test: test.cpp
	g++ -o test test.cpp

01_Initialization: 01_Initialization.cpp
	g++ -o 01_Initialization 01_Initialization.cpp

02_RoundoffError: 02_RoundoffError.cpp
	g++ -o 02_RoundoffError 02_RoundoffError.cpp

03_StringInitialization: 03_StringInitialization.cpp
	g++ -o 03_StringInitialization 03_StringInitialization.cpp
04_Const: 04_Const.cpp
	g++ -o 04_Const 04_Const.cpp
test: test.cpp
	g++ -o test test.cpp
test: test.cpp
	g++ -o test test.cpp
test: test.cpp
	g++ -o test test.cpp
test: test.cpp
	g++ -o test test.cpp