clean:
	-del -f *.exe
	
all:  test 01_Initialization 02_RoundoffError 03_StringInitialization 04_Const 05_FunctionPassingParameters 06_Vector 07_ReadingFile 08_CustomClass 09_RaiiPattern

test: test.cpp
	g++ -o test test.cpp

01_Initialization: 01_Initialization.cpp
	g++ -o 01_Initialization 01_Initialization.cpp

02_RoundoffError: 02_RoundoffError.cpp
	g++ -o 02_RoundoffError 02_RoundoffError.cpp

03_StringInitialization: 03_StringInitialization.cpp
	g++ -o 03_StringInitialization 03_StringInitialization.cpp
	
04_Const: 04_Const.cpp
	g++ -o 04_Const 04_Const.cpp
	
05_FunctionPassingParameters: 05_FunctionPassingParameters.cpp
	g++ -o 05_FunctionPassingParameters 05_FunctionPassingParameters.cpp

06_Vector: 06_Vector.cpp
	g++ -o 06_Vector 06_Vector.cpp

07_ReadingFile: 07_ReadingFile.cpp
	g++ -o 07_ReadingFile 07_ReadingFile.cpp

08_CustomClass: 08_CustomClass.cpp
	g++ -o 08_CustomClass 08_CustomClass.cpp
	
09_RaiiPattern: 09_RaiiPattern.cpp
	g++ -o 09_RaiiPattern 09_RaiiPattern.cpp
	
