clean:
	-del -f *.exe
	
all:  test 01_VectorOperations 02_VectorBufferOverflow 03_VectorSort 04_VectorInsertAndDelete

01_VectorOperations: 01_VectorOperations.cpp
	g++ -o 01_VectorOperations 01_VectorOperations.cpp

02_VectorBufferOverflow: 02_VectorBufferOverflow.cpp
	g++  -o 02_VectorBufferOverflow 02_VectorBufferOverflow.cpp

03_VectorSort: 03_VectorSort.cpp
	g++ -o 03_VectorSort 03_VectorSort.cpp

04_VectorInsertAndDelete: 04_VectorInsertAndDelete.cpp
	g++ -o 04_VectorInsertAndDelete 04_VectorInsertAndDelete.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp