clean:
	-del -f *.exe
	
all:  test 01_VectorOperations 02_VectorBufferOverflow

01_VectorOperations: 01_VectorOperations.cpp
	g++ -o 01_VectorOperations 01_VectorOperations.cpp

02_VectorBufferOverflow: 02_VectorBufferOverflow.cpp
	g++ -o 02_VectorBufferOverflow 02_VectorBufferOverflow.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp