clean:
	-del -f *.exe
	
all:  test 01_VectorOperations 02_VectorBufferOverflow 03_VectorSort 04_VectorInsertAndDelete 05_VectorFind 06_ArrayInitialization 07_ArrayOperations 08_ListInsertAndDelete 09_ListAccessElements 10_ListSorting

01_VectorOperations: 01_VectorOperations.cpp
	g++ -o 01_VectorOperations 01_VectorOperations.cpp

02_VectorBufferOverflow: 02_VectorBufferOverflow.cpp
	g++  -o 02_VectorBufferOverflow 02_VectorBufferOverflow.cpp

03_VectorSort: 03_VectorSort.cpp
	g++ -o 03_VectorSort 03_VectorSort.cpp

04_VectorInsertAndDelete: 04_VectorInsertAndDelete.cpp
	g++ -o 04_VectorInsertAndDelete 04_VectorInsertAndDelete.cpp

05_VectorFind: 05_VectorFind.cpp
	g++ -o 05_VectorFind 05_VectorFind.cpp

06_ArrayInitialization: 06_ArrayInitialization.cpp
	g++ -o 06_ArrayInitialization 06_ArrayInitialization.cpp

07_ArrayOperations: 07_ArrayOperations.cpp
	g++ -o 07_ArrayOperations 07_ArrayOperations.cpp

08_ListInsertAndDelete: 08_ListInsertAndDelete.cpp
	g++ -o 08_ListInsertAndDelete 08_ListInsertAndDelete.cpp

09_ListAccessElements: 09_ListAccessElements.cpp
	g++ -o 09_ListAccessElements 09_ListAccessElements.cpp

10_ListSorting: 10_ListSorting.cpp
	g++ -o 10_ListSorting 10_ListSorting.cpp
	
test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp
