clean:
	-del -f *.exe
	
all:  test  01_ArrayClass 02_ArrayClassImproved

test: 01_ArrayClass.cpp
	g++ -o 01_ArrayClass 01_ArrayClass.cpp

02_ArrayClassImproved: 02_ArrayClassImproved.cpp
	g++ -o 02_ArrayClassImproved 02_ArrayClassImproved.cpp

test: test.cpp
	g++ -o test test.cpp
	
test: test.cpp
	g++ -o test test.cpp
	
	
test: test.cpp
	g++ -o test test.cpp