clean:
	-del -f *.exe
	
all:  test 01_Set 02_SetOfCustomObjects 03_Map

test: test.cpp
	g++ -o test test.cpp

01_Set: 01_Set.cpp
	g++ -o 01_Set 01_Set.cpp

02_SetOfCustomObjects: 02_SetOfCustomObjects.cpp
	g++ -o 02_SetOfCustomObjects 02_SetOfCustomObjects.cpp

03_Map: 03_Map.cpp
	g++ -o 03_Map 03_Map.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp