clean:
	-del -f *.exe
	
all:  test 01_CStyleArray 02_CStyleString 03_FreeFunctionPointers

01_CStyleArray: 01_CStyleArray.cpp
	g++ -o 01_CStyleArray 01_CStyleArray.cpp

02_CStyleString: 02_CStyleString.cpp
	g++ -o 02_CStyleString 02_CStyleString.cpp

03_FreeFunctionPointers: 03_FreeFunctionPointers.cpp
	g++ -o 03_FreeFunctionPointers 03_FreeFunctionPointers.cpp

test: test.cpp
	g++ -o test test.cpp
	
test: test.cpp
	g++ -o test test.cpp
	
test: test.cpp
	g++ -o test test.cpp	
			
test: test.cpp
	g++ -o test test.cpp
			
	