clean:
	-del -f *.exe
	
all:  test 01_CStyleArray

01_CStyleArray: 01_CStyleArray.cpp
	g++ -o 01_CStyleArray 01_CStyleArray.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp
	
test: test.cpp
	g++ -o test test.cpp
	
test: test.cpp
	g++ -o test test.cpp	
			
test: test.cpp
	g++ -o test test.cpp
			
	