clean:
	-del -f *.exe
	
all:  test 01_Precision 02_StringsSwapCharacter

test: test.cpp
	g++ -o test test.cpp

01_Precision: 01_Precision.cpp
	g++ -o 01_Precision 01_Precision.cpp

02_StringsSwapCharacter: 02_StringsSwapCharacter.cpp
	g++ -o 02_StringsSwapCharacter 02_StringsSwapCharacter.cpp