clean:
	-del -f *.exe
	
all:  test  01_Precision 02_StringsSwapCharacter 03_StringStream 04_OperatorOverloading 05_VectorSorting 22_VariadicTemplate

test: test.cpp
	g++ -o test test.cpp
	
01_Precision: 01_Precision.cpp
	g++ -o 01_Precision 01_Precision.cpp

02_StringsSwapCharacter: 02_StringsSwapCharacter.cpp
	g++ -o 02_StringsSwapCharacter 02_StringsSwapCharacter.cpp

03_StringStream: 03_StringStream.cpp
	g++ -o 03_StringStream 03_StringStream.cpp

04_OperatorOverloading: 04_OperatorOverloading.cpp
	g++ -o 04_OperatorOverloading 04_OperatorOverloading.cpp	

05_VectorSorting: 05_VectorSorting.cpp
	g++ -o 05_VectorSorting 05_VectorSorting.cpp

22_VariadicTemplate: 22_VariadicTemplate.cpp
	g++ -o 22_VariadicTemplate 22_VariadicTemplate.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp
	
test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp
	
test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp
	
test: test.cpp
	g++ -o test test.cpp