clean:
	-del -f *.exe
	
all:  test 01_Precision 02_StringsSwapCharacter 03_StringStream 10_FormattingFloatingNumbers 11_InheritanceProtected 14_Preprocessor

test: test.cpp
	g++ -o test test.cpp

01_Precision: 01_Precision.cpp
	g++ -o 01_Precision 01_Precision.cpp

02_StringsSwapCharacter: 02_StringsSwapCharacter.cpp
	g++ -o 02_StringsSwapCharacter 02_StringsSwapCharacter.cpp

03_StringStream: 03_StringStream.cpp
	g++ -o 03_StringStream 03_StringStream.cpp

11_InheritanceProtected: 11_InheritanceProtected.cpp
	g++ -o 11_InheritanceProtected 11_InheritanceProtected.cpp

10_FormattingFloatingNumbers: 10_FormattingFloatingNumbers.cpp
	g++ -o 10_FormattingFloatingNumbers 10_FormattingFloatingNumbers.cpp

14_Preprocessor: 14_Preprocessor.cpp
	g++ -o 14_Preprocessor 14_Preprocessor.cpp
