clean:
	-del -f *.exe

all:  test 01_Counting 02_Finding 03_Sorting 04_ComparingCollections 05_Accumulate 06_ForEachLoop 07_Copying 08_Removing 09_Filling 10_Replace 11_Transform 12_Unique 13_Reverse 14_swap 15_BackInserterIterator 16_FronInserterIterator 17_ConstantIterator 18_PartialSortCopy 19_Swap

test: test.cpp
	g++ -o test test.cpp
		
01_Counting: 01_Counting.cpp
	g++ -o 01_Counting 01_Counting.cpp
	
02_Finding: 02_Finding.cpp
	g++ -o 02_Finding 02_Finding.cpp

03_Sorting: 03_Sorting.cpp
	g++ -o 03_Sorting 03_Sorting.cpp
	
04_ComparingCollections: 04_ComparingCollections.cpp
	g++ -o 04_ComparingCollections 04_ComparingCollections.cpp

05_Accumulate: 05_Accumulate.cpp
	g++ -o 05_Accumulate 05_Accumulate.cpp
	
06_ForEachLoop: 06_ForEachLoop.cpp
	g++ -o 06_ForEachLoop 06_ForEachLoop.cpp

07_Copying: 07_Copying.cpp
	g++ -o 07_Copying 07_Copying.cpp
	
08_Removing: 08_Removing.cpp
	g++ -o 08_Removing 08_Removing.cpp

09_Filling: 09_Filling.cpp
	g++ -o 09_Filling 09_Filling.cpp

10_Replace: 10_Replace.cpp
	g++ -o 10_Replace 10_Replace.cpp

11_Transform: 11_Transform.cpp
	g++ -o 11_Transform 11_Transform.cpp
	
12_Unique: 12_Unique.cpp
	g++ -o 12_Unique 12_Unique.cpp
	
13_Reverse: 13_Reverse.cpp
	g++ -o 13_Reverse 13_Reverse.cpp

14_swap: 14_swap.cpp
	g++ -o 14_swap 14_swap.cpp	
	
15_BackInserterIterator: 15_BackInserterIterator.cpp
	g++ -o 15_BackInserterIterator 15_BackInserterIterator.cpp

16_FronInserterIterator: 16_FronInserterIterator.cpp
	g++ -o 16_FronInserterIterator 16_FronInserterIterator.cpp
	
18_PartialSortCopy: 18_PartialSortCopy.cpp
	g++ -o 18_PartialSortCopy 18_PartialSortCopy.cpp
	
17_ConstantIterator: 17_ConstantIterator.cpp
	g++ -o 17_ConstantIterator 17_ConstantIterator.cpp	

19_Swap: 19_Swap.cpp
	g++ -o 19_Swap 19_Swap.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp
