clean:
	-del -f *.exe
	
all:  test 01_Counting 02_Finding 03_Sorting 04_ComparingCollections 05_Accumulate

test: test.cpp
	g++ -o test test.cpp
	
01_Counting: 01_Counting.cpp
	g++ -o 01_Counting 01_Counting.cpp
	
02_Finding: 02_Finding.cpp
	g++ -o 02_Finding 02_Finding.cpp

03_Sorting: 03_Sorting.cpp
	g++ -o 03_Sorting 03_Sorting.cpp
	
04_ComparingCollections: 04_ComparingCollections.cpp
	g++ -o 04_ComparingCollections 04_ComparingCollections.cpp

05_Accumulate: 05_Accumulate.cpp
	g++ -o 05_Accumulate 05_Accumulate.cpp