clean:
	-del -f *.exe
	
all:  test 01_LambdaCalledWithArguments

test: test.cpp
	g++ -o test test.cpp

01_LambdaCalledWithArguments: 01_LambdaCalledWithArguments.cpp
	g++ -o 01_LambdaCalledWithArguments 01_LambdaCalledWithArguments.cpp
	
test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp

test: test.cpp
	g++ -o test test.cpp
